# Generated by Django 4.1.6 on 2023-02-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=250)),
                ('author', models.CharField(default='', max_length=100)),
                ('price', models.FloatField()),
                ('description', models.CharField(default='', max_length=500)),
                ('address', models.CharField(default='', max_length=250)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
